[project]
name = "neural-networks"
version = "0.1.0"
description = "Lab projects for CSIT 6th semester Neural Networks"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.5",
]
